# Generated by Django 5.1.6 on 2025-03-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('artifact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to='artifact_icons/')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('weapon_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('attack_points', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to='weapon_icons/')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('most_enemies_killed', models.IntegerField(default=0)),
                ('most_days_survived', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('artifacts_earned', models.ManyToManyField(blank=True, to='gameApp.artifact')),
                ('weapons_earned', models.ManyToManyField(blank=True, to='gameApp.weapon')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('user_game', models.AutoField(primary_key=True, serialize=False)),
                ('player_hp', models.IntegerField(default=100)),
                ('player_ap', models.IntegerField(default=10)),
                ('player_speed', models.IntegerField(default=5)),
                ('player_food', models.IntegerField(default=10)),
                ('game_enemies_killed', models.IntegerField(default=0)),
                ('game_day', models.IntegerField(default=0)),
                ('game_difficulty', models.IntegerField(default=1)),
                ('game_map', models.IntegerField(default=1)),
                ('player_weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameApp.weapon')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
