# Generated by Django 5.1.6 on 2025-03-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='attack_points',
            new_name='damage',
        ),
        migrations.AddField(
            model_name='artifact',
            name='rarity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weapon',
            name='attack_message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weapon',
            name='rarity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='icon',
            field=models.ImageField(blank=True, upload_to='static/artifact_icons/'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='icon',
            field=models.ImageField(blank=True, upload_to='static/weapon_icons/'),
        ),
    ]
