# Generated by Django 5.1.6 on 2025-03-07 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gameApp', '0002_rename_attack_points_weapon_damage_artifact_rarity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('most_enemies_killed', models.IntegerField(default=0)),
                ('most_days_survived', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('artifacts_earned', models.ManyToManyField(blank=True, to='gameApp.artifact')),
                ('weapons_earned', models.ManyToManyField(blank=True, to='gameApp.weapon')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
