# Generated by Django 5.1.6 on 2025-03-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, upload_to='media/static/user_icons/'),
        ),
    ]
