# Generated by Django 5.1.6 on 2025-03-08 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0006_alter_game_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='user_game',
            new_name='game_id',
        ),
    ]
