# Generated by Django 5.1.6 on 2025-03-08 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0007_rename_user_game_game_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_id',
            new_name='user_game',
        ),
    ]
