# Generated by Django 5.1.6 on 2025-03-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0014_alter_userprofile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, default=(b'\x89PNG\r\n', b'\x1a\n', b'\x00\x00\x00\r', b'IHDR\x00\x00\x00d\x00\x00\x00d\x08\x02\x00\x00\x00\xff\x80\x02\x03\x00\x00\x00\xe8IDATx\x9c\xed\xd0\xc1\r', b'\xc0 \x10\xc0\xb0\xd2\xfdw>V /\x84dO\x10e\xcd\xcc\xc7\x99\xffv\xc0K\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'\xcc\n', b'6\xcf\xf1\x03\xc5\xca\xa6\xbch\x00\x00\x00\x00IEND\xaeB`\x82'), upload_to='static/user_icons/'),
        ),
    ]
