# Generated by Django 2.2.28 on 2025-03-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0033_auto_20250320_1043'),
        ('gameApp', '0032_auto_20250320_2239'),
    ]

    operations = [
    ]
